const $=s=>document.querySelector(s);let policies=[];let editingPolicy=null;
async function api(url,opt={}){const r=await fetch(url,opt);const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
async function call(url,body={}){return api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
function msg(t,e=false){$('#message').textContent=t;$('#message').className=`message${t?'':' hidden'}${e?' error':''}`}
$('#ask').onclick=async()=>{msg('正在检索当前生效文档…');try{const d=await call('/api/knowledge/answer',{question:$('#question').value});$('#decision').textContent=d.decision==='ANSWER'?'基于知识库的回答':'依据不足，已拒答';$('#generation').textContent=d.generation==='deterministic_excerpt_no_llm'?'确定性原文摘录 · 模型未调用':'';$('#answer-text').textContent=d.answer;$('#version').textContent=d.version_notice||'';$('#citations').replaceChildren(...d.citations.map(c=>{const el=document.createElement('article');el.className='citation';el.innerHTML=`<b></b><q></q>`;el.querySelector('b').textContent=`${c.title} · v${c.version} · 生效 ${c.effective_date}`;el.querySelector('q').textContent=c.quote;return el}));$('#answer').classList.remove('hidden');msg('')}catch(e){msg(e.message,true)}};
$('#evaluate').onclick=async()=>{msg('正在运行隔离的固定模拟问题…');try{const d=await call('/api/knowledge/evaluate');const values=[['检索命中率',d.retrieval_hit_rate],['引用准确率',d.citation_accuracy],['拒答准确率',d.refusal_accuracy],['问题数',d.case_count]];$('#metrics').innerHTML=values.map(([k,v])=>`<div class="metric"><b>${typeof v==='number'&&v<=1?(v*100).toFixed(0)+'%':v}</b><span>${k}</span></div>`).join('');$('#eval').classList.remove('hidden');msg(d.passed?'隔离评测集全部通过':'隔离评测集存在失败',!d.passed)}catch(e){msg(e.message,true)}};
function openEditor(policy=null){editingPolicy=policy?{id:policy.document_id,version:policy.version}:null;$('#policy-editor-title').textContent=policy?'编辑制度':'新增制度';[['#policy-id','document_id'],['#policy-title','title'],['#policy-version','version'],['#policy-date','effective_date'],['#policy-status','status'],['#policy-content','content']].forEach(([selector,key])=>{$(selector).value=policy?.[key]||($(selector).tagName==='SELECT'?'effective':'')});$('#policy-tags').value=(policy?.tags||[]).join(',');$('#policy-id').readOnly=Boolean(policy);$('#policy-version').readOnly=Boolean(policy);$('#policy-editor').classList.remove('hidden');$('#policy-editor').scrollIntoView({behavior:'smooth',block:'start'})}
function renderPolicies(data){policies=data.policies;$('#policy-summary').textContent=`${data.company.name} · ${policies.length} 个版本 · ${policies.filter(p=>p.status==='effective').length} 个生效版本`;const list=$('#policy-list');list.replaceChildren();if(!policies.length){const empty=document.createElement('p');empty.className='policy-empty';empty.textContent='当前没有制度。可新增制度，或在数据源页面恢复模拟公司数据。';list.append(empty);return}policies.forEach(p=>{const row=document.createElement('article');row.className='policy-row';const copy=document.createElement('div');const title=document.createElement('h3');title.textContent=p.title;const meta=document.createElement('p');meta.textContent=`${p.document_id} · v${p.version} · ${p.status} · ${p.effective_date}`;const excerpt=document.createElement('small');excerpt.textContent=p.content;copy.append(title,meta,excerpt);const actions=document.createElement('div');const edit=document.createElement('button');edit.type='button';edit.className='secondary-button';edit.textContent='编辑';edit.onclick=()=>openEditor(p);const remove=document.createElement('button');remove.type='button';remove.className='danger-button';remove.textContent='删除';remove.onclick=async()=>{if(!confirm(`删除“${p.title}”v${p.version}？`))return;try{await api(`/api/company-data/policies/${encodeURIComponent(p.document_id)}/${encodeURIComponent(p.version)}`,{method:'DELETE'});await loadPolicies();msg('制度版本已删除')}catch(e){msg(e.message,true)}};actions.append(edit,remove);row.append(copy,actions);list.append(row)})}
async function loadPolicies(){try{renderPolicies(await api('/api/company-data'))}catch(e){msg(e.message,true)}}
$('#new-policy').onclick=()=>openEditor();$('#cancel-policy').onclick=()=>$('#policy-editor').classList.add('hidden');$('#policy-form').onsubmit=async event=>{event.preventDefault();const payload={document_id:$('#policy-id').value.trim(),title:$('#policy-title').value.trim(),version:$('#policy-version').value.trim(),effective_date:$('#policy-date').value,status:$('#policy-status').value,tags:$('#policy-tags').value.split(',').map(x=>x.trim()).filter(Boolean),content:$('#policy-content').value.trim()};const url=editingPolicy?`/api/company-data/policies/${encodeURIComponent(editingPolicy.id)}/${encodeURIComponent(editingPolicy.version)}`:'/api/company-data/policies';try{await api(url,{method:editingPolicy?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('#policy-editor').classList.add('hidden');await loadPolicies();msg('制度已保存，后续问答和 Agent 将读取当前版本')}catch(e){msg(e.message,true)}};loadPolicies();
