import fs from 'node:fs/promises';
import { SpreadsheetFile, Workbook } from '@oai/artifact-tool';
const root=new URL('..',import.meta.url).pathname.replace(/^\/(.:)/,'$1');
const data=JSON.parse(await fs.readFile(`${root}/data/evaluation/phase6_reporting_data.json`,'utf8'));
const wb=Workbook.create(); const summary=wb.worksheets.add('周报摘要'); const risks=wb.worksheets.add('风险明细'); const actions=wb.worksheets.add('行动明细');
const font={name:'Arial',size:10}; for(const s of [summary,risks,actions]){s.showGridLines=false;s.getRange('A1:H40').format.font=font}
summary.getRange('A1:F1').merge(); summary.getRange('A1').values=[['项目风险周报']]; summary.getRange('A1').format.font={name:'Arial',size:18,bold:true,color:'#172033'}; summary.getRange('A2').values=[[`周期 ${data.period} · 固定模拟数据`]]; summary.getRange('A4:B10').values=[['指标','值'],['候选风险数',6],['高风险数',3],['已确认数',3],['误报数',2],['误报率',2/6],['逾期行动数',2]]; summary.getRange('A4:B4').format={fill:'#243B63',font:{name:'Arial',bold:true,color:'#FFFFFF'},horizontalAlignment:'center'}; summary.getRange('A4:B10').format.borders={preset:'all',style:'thin',color:'#D9D9D9'}; summary.getRange('B9').format.numberFormat='0.0%';
summary.getRange('D4:E9').values=[['日期','新增风险'],['2026-09-01',1],['2026-09-02',1],['2026-09-03',1],['2026-09-04',1],['2026-09-05',2]]; summary.getRange('D4:E4').format={fill:'#243B63',font:{name:'Arial',bold:true,color:'#FFFFFF'},horizontalAlignment:'center'}; const chart=summary.charts.add('line',summary.getRange('D4:E9')); chart.title='每日新增候选风险'; chart.hasLegend=false; chart.yAxis={numberFormatCode:'0',numberFormatSourceLinked:false,textStyle:{typeface:'Arial'}}; chart.setPosition('D11','J27');
risks.getRange('A1:F7').values=[['编号','日期','等级','状态','误报','处理小时'],...data.risks.map(r=>[r.id,new Date(`${r.date}T00:00:00`),r.level,r.status,r.false_positive,r.resolution_hours])]; actions.getRange('A1:E5').values=[['编号','行动','负责人角色','截止日期','状态'],...data.actions.map(a=>[a.id,a.title,a.owner_role,new Date(`${a.due_date}T00:00:00`),a.status])]; risks.getRange('B2:B7').format.numberFormat='yyyy-mm-dd'; actions.getRange('D2:D5').format.numberFormat='yyyy-mm-dd';
for(const [s,range] of [[risks,'A1:F7'],[actions,'A1:E5']]){s.getRange(range).format.borders={preset:'all',style:'thin',color:'#D9D9D9'};s.getRange(range.split(':')[0].replace(/\d+$/,'1')+':'+range.split(':')[1].replace(/\d+$/,'1')).format={fill:'#243B63',font:{name:'Arial',bold:true,color:'#FFFFFF'},horizontalAlignment:'center'};s.getUsedRange().format.autofitColumns();s.freezePanes.freezeRows(1)}
summary.getRange('A:B').format.columnWidth=20; summary.getRange('D:E').format.columnWidth=16;
const outDir=`${root}/data/reports`; await fs.mkdir(outDir,{recursive:true});
const inspect=await wb.inspect({kind:'table',sheetId:'周报摘要',range:'A1:F10',include:'values,formulas',tableMaxRows:12,tableMaxCols:8}); console.log(inspect.ndjson);
const errors=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:100},summary:'formula error scan'}); console.log(errors.ndjson);
for(const name of ['周报摘要','风险明细','行动明细']){const preview=await wb.render({sheetName:name,autoCrop:'all',scale:1,format:'png'});await fs.writeFile(`${root}/work/phase6-${name}.png`,new Uint8Array(await preview.arrayBuffer()))}
const file=await SpreadsheetFile.exportXlsx(wb); await file.save(`${outDir}/weekly-risk-report.xlsx`);
